#!/usr/bin/env bash
# A bash sripy that transfers a file from the client to a server using scp

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ 

if [ "$?" -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "Error: File transfer failed"
fi
