#!/usr/bin/env bash
# Script that execute commands to install nginx on web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx reload