#!/usr/bin/env bash
# A bash script taht configures the nginx server

sudo su root - &&\
sudo apt-get -y update &&\
sudo apt-get -y install nginx &&\

sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html ;\

sudo sed -i '/listen 80 default_server/a        rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default ;\
sudo service nginx restart
