#!/usr/bin/env bash
# Configure Nginx to add custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
