#!/usr/bin/env bash
# Configure Nginx to add custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header configuration
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
