#!/usr/bin/env bash
# Install and configure HAproxy for load balancing

sudo apt-get update
sudo apt-get install -y haproxy

echo "
frontend web
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 18.207.1.146:80 check
    server web-02 54.89.16.211:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
