#!/usr/bin/env bash
# Install and configure HAproxy for load balancing

sudo apt-get update
sudo apt-get install -y haproxy

echo "
frontend web
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 54.236.41.139:80 check
    server web-02 52.91.120.255:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
