#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

IP=$1
for ((i=1; i<=5; i++)); do
    ping -c 1 $IP
done
