#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

path_file="/var/run/myscript.pid"
echo "$$" > "$path_file"

trap 'echo "I hate the kill command" exit' 15

trap 'echo "Y U no love me?!"' 2

trap 'rm "$path_file"; exit' 3 15

while true; do
    echo "To infinity and beyond"
    sleep 2
done
