#!/usr/bin/env bash
# Write a Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

sigterm_handler() {
    echo "I am invincible!!!"
    exit 0
}

trap 'sigterm_handler' SIGTERM

a=0
while [ $a -lt 10 ]; do
    echo "To infinity and beyond"
    sleep 2
done
