#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

psrwd_file="/etc/passwd"

while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$psrwd_file"