#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

passwd_file="/etc/passwd"

while IFS=: read -r username _ userid groupid _ homedir shell
do
    user_info=$(finger "$username" 2>/dev/null | grep -E "Name:|Directory:|Shell:")

    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode, more info about the user here:"
    echo "$user_info"
    echo
done < "$passwd_file"