#!/usr/bin/env bash
# Configure ufw to allow 22 80 443 ports

# Install ufw
sudo apt-get update
sudo apt-get install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

# Enable SSH (port 22)
sudo ufw allow 22/tcp

# Enable HTTPS (port 443)
sudo ufw allow 443/tcp

# Enable HTTP (port 80)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable
