#!/bin/bash
# Bash script that set nginx as the user
# listening on port 8080

pkill "apache2"
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
